apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-headless
  namespace: expense
spec:
  selector: 
    project: expense
    component: mysql
    tier: db
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector: 
    project: expense
    component: mysql
    tier: db
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
  labels:
    project: expense
    component: mysql
    tier: db
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db 
  serviceName: "mysql-svc-headless"
  replicas: 2 # by default is 1
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db 
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: cekharch/mysql:v1
        volumeMounts:
        - name: mysql-statefulset
          mountPath: /var/log/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs-sc"
      resources:
        requests:
          storage: 1Gi